### ISSUE TITLE
Suggest to use SCS31 RC2 or later

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET-Compatibility-List#19]
After countless test installations on EET with the patch 2.5 and the updated version of SCS I would recommend to change the reference from SCSv30 to v31 RC2 or later and move that mod from the part 3 list to the part 2.
Rather than to make such a massive change myself, I think it is better for K4thos to approve this.
(This version has also been successfully used by players doing EET with the EE Install Tool and the sole issue found - Abazigal component - has been corrected in SCS right now.)

Change current list entry to this and move it to part 2 of the list:

<li><a href="https://github.com/Gibberlings3/SwordCoastStratagems/releases">Sword Coast Stratagems</a> v31 RC2 or later</li>

Alternatively, wait until RC3 which should be released very soon.

**Comment by K4thos** [comment]
yep, it should be moved. Although rather than linking to master.zip, I think it's better to use "Releases" page for mods hosted on Github. That way it's easier to view changelogs and mod readme file before downloading. So this link: https://github.com/Gibberlings3/SwordCoastStratagems/releases

**Comment by ALIENQuake** [comment]
You mean this link:
`http://lynxlynx.info/ie/modhub.php?Gibberlings3/SwordCoastStratagems&pre`
It will download last release or pre-release

**Comment by K4thos** [comment]
still the download link should not actually start download but point to the page with mod info and download link. I don't know 90% of mods on the list, so when I see some cool name I'd like to see what the mod is about rather then start downloading. I suspect more people have similar expectations. That's why I've used links like this: 
http://www.shsforums.net/files/file/913-custom-kits-the-spellsword/
http://gibberlings3.net/forums/index.php?app=downloads&showfile=931
instead of:
http://www.shsforums.net/files/download/913-custom-kits-the-spellsword/
http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=931

**Comment by RoxanneSHS** [comment]
I made the change using the overview link as suggested.
